apiVersion: v1
kind: Service
metadata:
  name: books-bff-app
  namespace: book-store-ns
  labels:
    run: books-bff-app
spec:
  ports:
  - port: 8002
    protocol: TCP
    targetPort: 8002
  selector:
    run: books-bff-app
  type: LoadBalancer