apiVersion: v1
kind: Service
metadata:
  name: customers-bff-app
  namespace: book-store-ns
  labels:
    run: customers-bff-app
spec:
  ports:
  - port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    run: customers-bff-app
  type: LoadBalancer